"""hide to roles in wfaction

Revision ID: 109f847af121
Revises: 6d48f4d7865e
Create Date: 2020-03-04 21:25:48.378053

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '109f847af121'
down_revision = '6d48f4d7865e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wfaction', sa.Column('hide_to_roles', mysql.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wfaction', 'hide_to_roles')
    # ### end Alembic commands ###
