"""adding status_needed_edit

Revision ID: 1bbfb9546f86
Revises: 6a8118e5ccf5
Create Date: 2020-02-22 14:10:07.074509

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1bbfb9546f86'
down_revision = '6a8118e5ccf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datadocfield', sa.Column('status_needed_edit', mysql.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('datadocfield', 'status_needed_edit')
    # ### end Alembic commands ###
