"""adding wfdoc

Revision ID: 211f79d36411
Revises: a4b24ce15866
Create Date: 2020-02-16 19:23:21.843255

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '211f79d36411'
down_revision = 'a4b24ce15866'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wfdoc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assocated_doctype_name', sa.String(length=120), nullable=True),
    sa.Column('prev_status', sa.String(length=120), nullable=True),
    sa.Column('current_status', sa.String(length=120), nullable=True),
    sa.Column('doc_data', mysql.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['assocated_doctype_name'], ['doctype.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wfdoc')
    # ### end Alembic commands ###
