"""empty message

Revision ID: 21adf58f00b9
Revises: 
Create Date: 2020-02-12 13:34:39.389561

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '21adf58f00b9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('wfstatus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('wf_action',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('assocated_doctype_id', sa.Integer(), nullable=True),
    sa.Column('need_prev_status_id', sa.Integer(), nullable=True),
    sa.Column('need_prev_current_id', sa.Integer(), nullable=True),
    sa.Column('leads_to_status_id', sa.Integer(), nullable=True),
    sa.Column('permitted_to_roles', mysql.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['assocated_doctype_id'], ['doctype.id'], ),
    sa.ForeignKeyConstraint(['leads_to_status_id'], ['wfstatus.id'], ),
    sa.ForeignKeyConstraint(['need_prev_current_id'], ['wfstatus.id'], ),
    sa.ForeignKeyConstraint(['need_prev_status_id'], ['wfstatus.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wf_action')
    op.drop_table('wfstatus')
    op.drop_table('doctype')
    # ### end Alembic commands ###
