"""draft_data to doc_data in Draftdb

Revision ID: 4a1478a35f9c
Revises: ca0b92f5e03e
Create Date: 2020-03-14 11:46:34.942480

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4a1478a35f9c'
down_revision = 'ca0b92f5e03e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('draftdata', sa.Column('doc_data', mysql.JSON(), nullable=True))
    op.drop_column('draftdata', 'draft_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('draftdata', sa.Column('draft_data', mysql.JSON(), nullable=True))
    op.drop_column('draftdata', 'doc_data')
    # ### end Alembic commands ###
