"""recraeate db after retro and insternal use added in field 

Revision ID: 4f1371de0bff
Revises: 
Create Date: 2020-03-22 12:53:58.684233

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4f1371de0bff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctype',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('primkey_in_datadoc', sa.String(length=120), nullable=False),
    sa.Column('roles_to_view_audit', mysql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('name'),
    sa.UniqueConstraint('name')
    )
    op.create_table('wfstatus',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('name'),
    sa.UniqueConstraint('name')
    )
    op.create_table('datadocfield',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('associated_doctype_name', sa.String(length=120), nullable=True),
    sa.Column('ftype', sa.String(length=120), nullable=False),
    sa.Column('flength', sa.Integer(), nullable=False),
    sa.Column('status_needed_edit', mysql.JSON(), nullable=True),
    sa.Column('wfc_filter', sa.String(length=120), nullable=True),
    sa.Column('wfc_filter_to_roles', mysql.JSON(), nullable=True),
    sa.Column('retro', sa.String(length=4), nullable=True),
    sa.Column('internaluse', sa.String(length=4), nullable=True),
    sa.ForeignKeyConstraint(['associated_doctype_name'], ['doctype.name'], ),
    sa.PrimaryKeyConstraint('name'),
    sa.UniqueConstraint('name')
    )
    op.create_table('wfaction',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('associated_doctype_name', sa.String(length=120), nullable=True),
    sa.Column('need_current_status', mysql.JSON(), nullable=True),
    sa.Column('leads_to_status', sa.String(length=120), nullable=False),
    sa.Column('permitted_to_roles', mysql.JSON(), nullable=True),
    sa.Column('hide_to_roles', mysql.JSON(), nullable=True),
    sa.Column('undo_prev_hide_for', mysql.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['associated_doctype_name'], ['doctype.name'], ),
    sa.PrimaryKeyConstraint('name'),
    sa.UniqueConstraint('name')
    )
    op.create_table('wfdoc',
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('associated_doctype_name', sa.String(length=120), nullable=True),
    sa.Column('prev_status', sa.String(length=120), nullable=True),
    sa.Column('current_status', sa.String(length=120), nullable=True),
    sa.Column('doc_data', mysql.JSON(), nullable=True),
    sa.Column('has_draft_for_roles', mysql.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['associated_doctype_name'], ['doctype.name'], ),
    sa.PrimaryKeyConstraint('name'),
    sa.UniqueConstraint('name')
    )
    op.create_table('draftdata',
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('drafted_by', sa.String(length=120), nullable=True),
    sa.Column('target_role', mysql.JSON(), nullable=True),
    sa.Column('wfdoc_name', sa.String(length=120), nullable=True),
    sa.Column('doc_data', mysql.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['wfdoc_name'], ['wfdoc.name'], ),
    sa.PrimaryKeyConstraint('name'),
    sa.UniqueConstraint('name')
    )
    op.create_table('holddoc',
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('target_role', sa.String(length=120), nullable=True),
    sa.Column('reason', sa.String(length=120), nullable=True),
    sa.Column('wfdoc_name', sa.String(length=120), nullable=True),
    sa.Column('associated_doctype_name', sa.String(length=120), nullable=True),
    sa.Column('prev_status', sa.String(length=120), nullable=True),
    sa.Column('current_status', sa.String(length=120), nullable=True),
    sa.Column('doc_data', mysql.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['associated_doctype_name'], ['doctype.name'], ),
    sa.ForeignKeyConstraint(['wfdoc_name'], ['wfdoc.name'], ),
    sa.PrimaryKeyConstraint('name'),
    sa.UniqueConstraint('name')
    )
    op.create_table('wfdocaudit',
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('wfdoc_name', sa.String(length=120), nullable=True),
    sa.Column('username', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('time_stamp', sa.String(length=120), nullable=True),
    sa.Column('client_address', sa.String(length=120), nullable=True),
    sa.Column('org', sa.String(length=120), nullable=True),
    sa.Column('orgunit', sa.String(length=120), nullable=True),
    sa.Column('department', sa.String(length=120), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=True),
    sa.Column('roles', mysql.JSON(), nullable=True),
    sa.Column('data', mysql.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['wfdoc_name'], ['wfdoc.name'], ),
    sa.PrimaryKeyConstraint('name'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wfdocaudit')
    op.drop_table('holddoc')
    op.drop_table('draftdata')
    op.drop_table('wfdoc')
    op.drop_table('wfaction')
    op.drop_table('datadocfield')
    op.drop_table('wfstatus')
    op.drop_table('doctype')
    # ### end Alembic commands ###
