"""empty message

Revision ID: 58c3f3f4dc26
Revises: 21adf58f00b9
Create Date: 2020-02-12 13:36:45.230224

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '58c3f3f4dc26'
down_revision = '21adf58f00b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wfaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('assocated_doctype_id', sa.Integer(), nullable=True),
    sa.Column('need_prev_status_id', sa.Integer(), nullable=True),
    sa.Column('need_prev_current_id', sa.Integer(), nullable=True),
    sa.Column('leads_to_status_id', sa.Integer(), nullable=True),
    sa.Column('permitted_to_roles', mysql.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['assocated_doctype_id'], ['doctype.id'], ),
    sa.ForeignKeyConstraint(['leads_to_status_id'], ['wfstatus.id'], ),
    sa.ForeignKeyConstraint(['need_prev_current_id'], ['wfstatus.id'], ),
    sa.ForeignKeyConstraint(['need_prev_status_id'], ['wfstatus.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_index('name', table_name='wf_action')
    op.drop_table('wf_action')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wf_action',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('assocated_doctype_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('need_prev_status_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('need_prev_current_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('leads_to_status_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('permitted_to_roles', mysql.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['assocated_doctype_id'], ['doctype.id'], name='wf_action_ibfk_1'),
    sa.ForeignKeyConstraint(['leads_to_status_id'], ['wfstatus.id'], name='wf_action_ibfk_2'),
    sa.ForeignKeyConstraint(['need_prev_current_id'], ['wfstatus.id'], name='wf_action_ibfk_3'),
    sa.ForeignKeyConstraint(['need_prev_status_id'], ['wfstatus.id'], name='wf_action_ibfk_4'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('name', 'wf_action', ['name'], unique=True)
    op.drop_table('wfaction')
    # ### end Alembic commands ###
