"""adding datafields

Revision ID: 6567e4cdf8a6
Revises: dcc3a9b59bdf
Create Date: 2020-02-21 09:15:53.491762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6567e4cdf8a6'
down_revision = 'dcc3a9b59bdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datadocfield',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('assocated_doctype_name', sa.String(length=120), nullable=True),
    sa.Column('ftype', sa.String(length=120), nullable=False),
    sa.Column('flength', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assocated_doctype_name'], ['doctype.name'], ),
    sa.PrimaryKeyConstraint('name'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('datadocfield')
    # ### end Alembic commands ###
