"""Holddoc

Revision ID: 6d48f4d7865e
Revises: 6036e24e361d
Create Date: 2020-03-04 17:43:02.652730

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6d48f4d7865e'
down_revision = '6036e24e361d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('holddoc',
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('target_role', sa.String(length=120), nullable=True),
    sa.Column('reason', sa.String(length=120), nullable=True),
    sa.Column('wfdoc_name', sa.String(length=120), nullable=True),
    sa.Column('prev_status', sa.String(length=120), nullable=True),
    sa.Column('current_status', sa.String(length=120), nullable=True),
    sa.Column('doc_data', mysql.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['wfdoc_name'], ['wfdoc.name'], ),
    sa.PrimaryKeyConstraint('name'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('holddoc')
    # ### end Alembic commands ###
