"""wfc_filtr in docdatafield 

Revision ID: 7edafeb6ce37
Revises: ed2c3d2e3c8e
Create Date: 2020-03-11 19:20:16.732036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7edafeb6ce37'
down_revision = 'ed2c3d2e3c8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datadocfield', sa.Column('wfc_filter', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('datadocfield', 'wfc_filter')
    # ### end Alembic commands ###
