"""draft data table 

Revision ID: ca0b92f5e03e
Revises: 434cfb40bbe4
Create Date: 2020-03-13 10:05:07.057021

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ca0b92f5e03e'
down_revision = '434cfb40bbe4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('draftdata',
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('drafted_by', sa.String(length=120), nullable=True),
    sa.Column('target_role', mysql.JSON(), nullable=True),
    sa.Column('wfdoc_name', sa.String(length=120), nullable=True),
    sa.Column('draft_data', mysql.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['wfdoc_name'], ['wfdoc.name'], ),
    sa.PrimaryKeyConstraint('name'),
    sa.UniqueConstraint('name')
    )
    op.add_column('wfdoc', sa.Column('has_draft_for_roles', mysql.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wfdoc', 'has_draft_for_roles')
    op.drop_table('draftdata')
    # ### end Alembic commands ###
