"""adding primkey_in_datadoc in Doctype

Revision ID: e2e0c6f10cde
Revises: f8b8037fe940
Create Date: 2020-02-19 15:59:52.880419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2e0c6f10cde'
down_revision = 'f8b8037fe940'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctype', sa.Column('primkey_in_datadoc', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctype', 'primkey_in_datadoc')
    # ### end Alembic commands ###
