"""wfc_filter_to_roles in docdatafield 

Revision ID: 434cfb40bbe4
Revises: 7edafeb6ce37
Create Date: 2020-03-12 10:15:07.780311

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '434cfb40bbe4'
down_revision = '7edafeb6ce37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datadocfield', sa.Column('wfc_filter_to_roles', mysql.JSON(), nullable=True))
    op.alter_column('datadocfield', 'wfc_filter',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('datadocfield', 'wfc_filter',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    op.drop_column('datadocfield', 'wfc_filter_to_roles')
    # ### end Alembic commands ###
