"""action in audit table

Revision ID: 62fc268c2cf8
Revises: fc6fcb4616f4
Create Date: 2020-02-29 19:52:19.673407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62fc268c2cf8'
down_revision = 'fc6fcb4616f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wfdocaudit', sa.Column('action', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wfdocaudit', 'action')
    # ### end Alembic commands ###
