"""field name corrected assocated_doctype

Revision ID: 6a8118e5ccf5
Revises: 6567e4cdf8a6
Create Date: 2020-02-21 13:41:53.950867

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6a8118e5ccf5'
down_revision = '6567e4cdf8a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datadocfield', sa.Column('associated_doctype_name', sa.String(length=120), nullable=True))
    op.drop_constraint('datadocfield_ibfk_1', 'datadocfield', type_='foreignkey')
    op.create_foreign_key(None, 'datadocfield', 'doctype', ['associated_doctype_name'], ['name'])
    op.drop_column('datadocfield', 'assocated_doctype_name')
    op.add_column('wfaction', sa.Column('associated_doctype_name', sa.String(length=120), nullable=True))
    op.drop_constraint('wfaction_ibfk_1', 'wfaction', type_='foreignkey')
    op.create_foreign_key(None, 'wfaction', 'doctype', ['associated_doctype_name'], ['name'])
    op.drop_column('wfaction', 'assocated_doctype_name')
    op.add_column('wfdoc', sa.Column('associated_doctype_name', sa.String(length=120), nullable=True))
    op.drop_constraint('wfdoc_ibfk_1', 'wfdoc', type_='foreignkey')
    op.create_foreign_key(None, 'wfdoc', 'doctype', ['associated_doctype_name'], ['name'])
    op.drop_column('wfdoc', 'assocated_doctype_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wfdoc', sa.Column('assocated_doctype_name', mysql.VARCHAR(length=120), nullable=True))
    op.drop_constraint(None, 'wfdoc', type_='foreignkey')
    op.create_foreign_key('wfdoc_ibfk_1', 'wfdoc', 'doctype', ['assocated_doctype_name'], ['name'])
    op.drop_column('wfdoc', 'associated_doctype_name')
    op.add_column('wfaction', sa.Column('assocated_doctype_name', mysql.VARCHAR(length=120), nullable=True))
    op.drop_constraint(None, 'wfaction', type_='foreignkey')
    op.create_foreign_key('wfaction_ibfk_1', 'wfaction', 'doctype', ['assocated_doctype_name'], ['name'])
    op.drop_column('wfaction', 'associated_doctype_name')
    op.add_column('datadocfield', sa.Column('assocated_doctype_name', mysql.VARCHAR(length=120), nullable=True))
    op.drop_constraint(None, 'datadocfield', type_='foreignkey')
    op.create_foreign_key('datadocfield_ibfk_1', 'datadocfield', 'doctype', ['assocated_doctype_name'], ['name'])
    op.drop_column('datadocfield', 'associated_doctype_name')
    # ### end Alembic commands ###
