"""retro and system in datadocfiled

Revision ID: 6da87f8410eb
Revises: 4a1478a35f9c
Create Date: 2020-03-22 11:34:16.963758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6da87f8410eb'
down_revision = '4a1478a35f9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datadocfield', sa.Column('retro', sa.Boolean(), nullable=True))
    op.add_column('datadocfield', sa.Column('system', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('datadocfield', 'system')
    op.drop_column('datadocfield', 'retro')
    # ### end Alembic commands ###
