""" system changed as internal use 

Revision ID: bb2d5b0bbddb
Revises: 6da87f8410eb
Create Date: 2020-03-22 12:44:36.925613

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bb2d5b0bbddb'
down_revision = '6da87f8410eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datadocfield', sa.Column('internaluse', sa.String(), nullable=True))
    op.drop_column('datadocfield', 'system')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datadocfield', sa.Column('system', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('datadocfield', 'internaluse')
    # ### end Alembic commands ###
