"""wfdoc primary key changed from id to name

Revision ID: dcc3a9b59bdf
Revises: e2e0c6f10cde
Create Date: 2020-02-19 18:49:22.324250

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dcc3a9b59bdf'
down_revision = 'e2e0c6f10cde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wfdoc', sa.Column('name', sa.String(length=500), nullable=False))
    op.drop_index('id', table_name='wfdoc')
    op.create_unique_constraint(None, 'wfdoc', ['name'])
    op.drop_column('wfdoc', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wfdoc', sa.Column('id', mysql.VARCHAR(length=500), nullable=False))
    op.drop_constraint(None, 'wfdoc', type_='unique')
    op.create_index('id', 'wfdoc', ['id'], unique=True)
    op.drop_column('wfdoc', 'name')
    # ### end Alembic commands ###
