"""primkey_from_docdata made primary key

Revision ID: e77ddac5cb0f
Revises: 
Create Date: 2020-02-18 16:05:50.399768

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e77ddac5cb0f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctype',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('name'),
    sa.UniqueConstraint('name')
    )
    op.create_table('wfstatus',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('name'),
    sa.UniqueConstraint('name')
    )
    op.create_table('wfaction',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('assocated_doctype_name', sa.String(length=120), nullable=True),
    sa.Column('need_prev_status', sa.String(length=120), nullable=False),
    sa.Column('need_current_status', sa.String(length=120), nullable=False),
    sa.Column('leads_to_status', sa.String(length=120), nullable=False),
    sa.Column('permitted_to_roles', mysql.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['assocated_doctype_name'], ['doctype.name'], ),
    sa.PrimaryKeyConstraint('name'),
    sa.UniqueConstraint('name')
    )
    op.create_table('wfdoc',
    sa.Column('primvalue_of_docdata', sa.String(length=500), nullable=False),
    sa.Column('assocated_doctype_name', sa.String(length=120), nullable=True),
    sa.Column('prev_status', sa.String(length=120), nullable=True),
    sa.Column('current_status', sa.String(length=120), nullable=True),
    sa.Column('doc_data', mysql.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['assocated_doctype_name'], ['doctype.name'], ),
    sa.PrimaryKeyConstraint('primvalue_of_docdata'),
    sa.UniqueConstraint('primvalue_of_docdata')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wfdoc')
    op.drop_table('wfaction')
    op.drop_table('wfstatus')
    op.drop_table('doctype')
    # ### end Alembic commands ###
