"""need_current_status as list in wfaction and remove prev_stat 

Revision ID: ed2c3d2e3c8e
Revises: c6d375b8d76b
Create Date: 2020-03-06 18:41:59.117321

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ed2c3d2e3c8e'
down_revision = 'c6d375b8d76b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wfaction', 'need_current_status',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.drop_column('wfaction', 'need_prev_status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wfaction', sa.Column('need_prev_status', mysql.VARCHAR(length=120), nullable=False))
    op.alter_column('wfaction', 'need_current_status',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    # ### end Alembic commands ###
