"""audit table

Revision ID: fc6fcb4616f4
Revises: 1bbfb9546f86
Create Date: 2020-02-29 15:50:39.436236

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fc6fcb4616f4'
down_revision = '1bbfb9546f86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wfdocaudit',
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('wfdoc_name', sa.String(length=120), nullable=True),
    sa.Column('username', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('time_stamp', sa.String(length=120), nullable=True),
    sa.Column('client_address', sa.String(length=120), nullable=True),
    sa.Column('org', sa.String(length=120), nullable=True),
    sa.Column('orgunit', sa.String(length=120), nullable=True),
    sa.Column('department', sa.String(length=120), nullable=True),
    sa.Column('roles', mysql.JSON(), nullable=True),
    sa.Column('data', mysql.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['wfdoc_name'], ['wfdoc.name'], ),
    sa.PrimaryKeyConstraint('name'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wfdocaudit')
    # ### end Alembic commands ###
